### ISSUE TITLE
Possibility to get the double of the "normal" amount when win

### ISSUE THREAD

**Issue by DickerSauerlaender** [pirak/firebot-gambling-script#168]
Example:
0: Jackpot
1-50: Loose
51-100: Win

In this example, you win the multiplicator X from 51-97 and you have the setting-option for a double of the multiplicator, in this case 98-100.

**Comment by pirak** [comment]
Sounds like a good idea, but I think I could make it more flexible. The settings menu should have options where a user can enter an arbitrary number of ranges each with its own multiplicator, plus a separate value for the jackpot that overrides any multiplicator for that number. Then a user can define exactly what you describe, but also more flexible setups with an arbitrary number of ranges would be possible. E.g., 
- 1-25: -1 (lose all points entered)
- 26-49: -0.5
- 50-50: 0 (no points lost)
- 51-97: 1
- 98-100: 2

I probably won’t have time in the next few weeks to implement it, but that sounds like a nice addition to the script. If anyone wants to implement (parts of) it and make a PR, you’re more than welcome.

**Comment by DickerSauerlaender** [comment]
@pirak i hope you had a good start into this new year?! Are there any news for your cool script's update? =)

**Comment by pirak** [comment]
Nice to see that you are still interested. Sorry for the long silence on my end.

The actual implementation of the necessary UI settings and the payout calculation is done. The only missing part is the validation of the input data. I need to experiment with that a bit since the UI and where the other parts of the script run are separated within Firebot. I’ve got some experimental prototype for the communication. The implementation should not be too complicated, it is just a bit hard to test and debug. So once I make the communication work, then the remaining parts should be easy.
I hope to find the time for that somewhen soon and then finish the feature implementation.

**Comment by pirak** [comment]
It was actually easier than I thought. In #397 I uploaded a version of the script with the new feature.
Feel free to test that. If you don’t encounter any issues, I’ll merge that afterwards.

**Comment by DickerSauerlaender** [comment]
Awesome @pirak !!! =) Thank you so much, i will test it out in the next streams and give you feedback. Thanks for your passion and help!

**Comment by DickerSauerlaender** [comment]
First feedback: everything seems to work fine! =)

**Comment by pirak** [comment]
Thanks for testing!
I’m going to merge the feature then. If you notice any problems, just open another issue.
